import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowLeft } from "lucide-react"

export const metadata = {
  title: "Terms of Service - Fablito",
  description: "Terms of Service for Fablito",
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background pt-20 pb-12">
      <div className="max-w-3xl mx-auto px-4">
        <Link href="/">
          <Button variant="ghost" className="mb-6 text-white hover:text-white/80 hover:bg-white/10">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back
          </Button>
        </Link>

        <div className="magic-card rounded-2xl p-6 md:p-8">
          <h1 className="text-3xl font-bold text-white mb-6">Terms of Service</h1>

          <div className="space-y-6 text-white/80">
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing and using Fablito, you accept and agree to be bound by the terms
                and conditions of this agreement.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">2. Use of Service</h2>
              <p>
                Fablito provides AI-generated personalized stories for children. You agree to use
                the service only for lawful purposes and in accordance with these terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">3. User Content</h2>
              <p>
                You retain ownership of any content you provide (such as names, story ideas).
                By using our service, you grant us permission to use this content to generate stories.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">4. AI-Generated Content</h2>
              <p>
                Stories and images are generated by artificial intelligence. While we strive for
                quality and appropriateness, we cannot guarantee the content will meet all expectations.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">5. Limitation of Liability</h2>
              <p>
                Fablito is provided "as is" without warranties of any kind. We are not liable for
                any damages arising from the use of our service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">6. Contact</h2>
              <p>
                For questions about these terms, please contact us through our GitHub repository.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  )
}
